// <auto-generated />
namespace WU15.Azure.ServiceManager.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_some_nulls_on_Serviceticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_some_nulls_on_Serviceticket));
        
        string IMigrationMetadata.Id
        {
            get { return "201702010823149_Added_some_nulls_on_Serviceticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
